print("ola mundo")
print("Hello, World!")
print("Bonjour le monde!")
print("Hola, Mundo!")
print("Hallo, Welt!")
print("Ciao, Mondo!")
print("こんにちは世界！")
print("안녕하세요 세계!")
print("Привет, мир!")
print("مرحبا بالعالم!")
print("שלום עולם!")
print("नमस्ते दुनिया!")
print("Olá, Mundo!")
print("Hej världen!")
print("Hej Verden!")
